cms/cms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.redirect_home),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('conference/', include('conference.urls')),
    path('reviewer/', include('reviewer.urls')),
    path('gsp/', include('gsp.urls')),
    path('area_chair/', include('area_chair.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cms/reviewer/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('redirect_signup', views.redirect_signup, name='redirect_signup'),
    path('redirect_login', views.redirect_login, name='redirect_login'),
    path('redirect_logout', views.redirect_logout, name='redirect_logout'),
    path('redirect_userpage', views.redirect_userpage, name='redirect_userpage'),
    path('assigned_papers', views.assigned_papers, name='assigned_papers'),
    path('<str:conf_name>/apply_as_a_reviewer', views.apply_as_a_reviewer,
         name='apply_as_a_reviewer'),
    path('<str:conf_name>/make_review/<str:title>',
         views.make_review, name='make_review'),
    path('<str:conf_name>/edit_review/<str:title>',
         views.edit_review, name='edit_review'),
    path('<str:conf_name>/invite_reviewers/',
         views.invite_reviewers, name='invite_reviewers'),
    path('<str:conf_name>/automated_reviewer_assignment/',
         views.automated_reviewer_assignment, name='automated_reviewer_assignment'),
    #     path('<str:conf_name>/manual_reviewer_assignment/',
    #          views.manual_reviewer_assignment, name='manual_reviewer_assignment'),
]

cms/urls.py
from django.urls import include, path

urlpatterns = [
    path('/', include('accounts.urls'))
]

cms/accounts/models.py
from django.db import models
from django.utils import timezone


class User(models.Model):
    email = models.TextField(null=False, primary_key=True)
    password = models.TextField()
    name = models.TextField()


class ResearchProfile(models.Model):
    person = models.ForeignKey(User, on_delete=models.CASCADE)
    institution = models.CharField(max_length=250)
    research_interests = models.CharField(max_length=500)
    highest_degree = models.CharField(max_length=250)
    google_scholar = models.CharField(max_length=250)


class SecurityQuestions(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='user')
    question = models.TextField(null=False)
    answer = models.TextField(null=False)

cms/reviewer/models.py
from django.db import models
from accounts.models import User
from conference.models import Conference
from django.core.validators import MinValueValidator
from gsp.models import PaperSubmission


class Reviewer(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE)
    conference = models.ForeignKey(
        Conference, on_delete=models.CASCADE)
    prior_reviewing_experience = models.CharField(max_length=250, blank=True)
    prior_research_paper_submissions = models.PositiveIntegerField(default=0)
    area_expertise = models.CharField(max_length=250)
    paper_review_limit = models.PositiveIntegerField(
        validators=[MinValueValidator(3)])

    def __str__(self):
        return self.user.name


class Review(models.Model):
    paper_submission = models.ForeignKey(
        PaperSubmission, on_delete=models.CASCADE)
    reviewer = models.ForeignKey(Reviewer, on_delete=models.CASCADE)
    summary = models.TextField(blank=True)
    novelty = models.TextField(blank=True)
    impact = models.TextField(blank=True)
    strong_points = models.TextField(blank=True)
    weak_points = models.TextField(blank=True)

    def __str__(self):
        return self.paper_submission.title


class InvitedReviewers(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    conference = models.ForeignKey(Conference, on_delete=models.CASCADE)


class AssignedReviewers(models.Model):
    reviewer = models.ForeignKey(Reviewer, on_delete=models.CASCADE)
    conference = models.ForeignKey(Conference, on_delete=models.CASCADE)
    paper_submission = models.ForeignKey(
        PaperSubmission, on_delete=models.CASCADE)

cms/reviewer/forms.py
from django import forms
from .models import Reviewer, Review
from conference import utils as conf_utils


class ReviewerForm(forms.ModelForm):
    class Meta:
        model = Reviewer
        exclude = ['user', 'conference']
        widgets = {
            'paper_review_limit': forms.TextInput(attrs={'placeholder': 'Enter atleast 3 papers to review'})
        }

    def __init__(self, *args, **kwargs):
        if "conf_subject_areas" not in kwargs:
            super(ReviewerForm, self).__init__(*args, **kwargs)
        else:
            area_expertises = kwargs.pop('conf_subject_areas')
            AREA_EXPERTISE_CHOICES = [
                (area_expertise, area_expertise) for area_expertise in area_expertises]
            super(ReviewerForm, self).__init__(*args, **kwargs)
            self.fields['area_expertise'] = forms.ChoiceField(
                choices=AREA_EXPERTISE_CHOICES)


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        exclude = ['paper_submission', 'reviewer']


class InviteReviewersForm(forms.Form):
    pass

    # def __init__(self, *args, **kwargs):
    #     if "conf_users" not in kwargs:
    #         super(InviteReviewersForm, self).__init__(*args, **kwargs)
    #     else:
    #         conf_users = kwargs.pop('conf_users')
    #         CONF_USERS = [
    #             (conf_user.name, conf_user.name) for conf_user in conf_users]
    #         super(InviteReviewersForm, self).__init__(*args, **kwargs)
    #         self.fields['conference_users'] = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
    #                                                                     choices=CONF_USERS)
    #         self.fields['research_interests'].widget.attrs['readonly'] = True

cms/reviewer/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from django.utils import timezone
from .models import Reviewer, InvitedReviewers, AssignedReviewers
from .forms import ReviewerForm, ReviewForm, InviteReviewersForm
from accounts import utils
from . import data_access_layer as reviewer_dao
from accounts import data_access_layer as accounts_dao
from conference import data_access_layer as conference_dao
from area_chair.models import AssignedAreaChairs, AreaChair
from gsp import data_access_layer as gsp_dao
from conference import views as conf_views
from .utils import assign_reviewers, sufficient_reviewers_check_of_conf
from .constants import REVIEWER_APPLICATION_DEADLINE, INVITE_REVIEWERS_DEADLINE, MIN_PAPER_REVIEW_LIMIT


def redirect_signup(request):
    return redirect('/accounts/signup')


def redirect_login(request):
    return redirect('/accounts/login')


def redirect_logout(request):
    return redirect('/accounts/logout')


def redirect_userpage(request):
    return redirect('/accounts/userpage')


def apply_as_a_reviewer(request, conf_name):
    is_logged_in = utils.check_login(request)
    if is_logged_in:
        conf = conference_dao.get_conference_by_name(conf_name)
        cur_user_email = request.COOKIES.get('email')
        # check if user is in the list of invited reviewers
        invited_reviewers_emails = reviewer_dao.get_invited_reviewers_emails_of_conf(
            conf_name)
        if cur_user_email not in invited_reviewers_emails:
            messages.error(
                request, f"Sorry, you are not invited reviewer for this conference")
            return redirect(conf_views.list_conferences)
        # reviewer application deadline check
        cur_time = timezone.now()
        if (cur_time - conf.paper_submission_deadline).days > REVIEWER_APPLICATION_DEADLINE:
            messages.error(
                request, f"Sorry, Reviewer application deadline has been elapsed")
            return redirect(conf_views.list_conferences)
        if request.method == "POST":
            form = ReviewerForm(request.POST)
            if form.is_valid():
                reviewer = form.save(commit=False)
                reviewer.conference = conference_dao.get_conference_by_name(
                    conf_name)
                reviewer.user = accounts_dao.obtain_user_by_email(
                    request.COOKIES.get('email'))
                reviewer.save()
                messages.info(
                    request, f"You have sucessfully applied for the reviewer")
                # pass messages to list conf
                return redirect(conf_views.list_conferences)
            return render(request, "apply_as_a_reviewer.html", {"is_logged_in": is_logged_in, "form": form, "name": conf_name})
        else:
            conf_subject_areas = conf.subject_areas.split(',')
            form = ReviewerForm(conf_subject_areas=conf_subject_areas)
        return render(request, "apply_as_a_reviewer.html", {"is_logged_in": is_logged_in, "form": form, "name": conf_name})
    return redirect('/accounts/login')


def assigned_papers(request):
    is_logged_in = utils.check_login(request)
    if is_logged_in:
        current_reviewer_confs = Reviewer.objects.all().filter(
            user=request.COOKIES.get('email'))
        conf_assignments = []
        for cf in current_reviewer_confs:
            current_conf_assignment = AssignedReviewers.objects.all().filter(reviewer=cf)
            current_conf_assigned_papers = [
                a.paper_submission for a in current_conf_assignment]
            conf_assignments.extend(current_conf_assigned_papers)

        # code for Area Chair assignments
        current_ac_confs = AreaChair.objects.all().filter(
            user=request.COOKIES.get('email'))
        ac_assignments = []
        for ac in current_ac_confs:
            ac_current_conf_assignment = AssignedAreaChairs.objects.all().filter(area_chair=ac)
            ac_current_conf_assigned_papers = [
                a.paper_submission for a in ac_current_conf_assignment]
            ac_assignments.extend(ac_current_conf_assigned_papers)

        return render(request, "assigned_papers.html", {"is_logged_in": is_logged_in,
                                                        "conf_assignments": conf_assignments,
                                                        "ac_assignments": ac_assignments})
    return redirect('/accounts/login')


def make_review(request, conf_name, title):
    is_logged_in = utils.check_login(request)
    if is_logged_in:
        cur_user_email = request.COOKIES.get('email')
        # check if reviewer is assigned to review the paper
        try:
            reviewer = Reviewer.objects.get(
                user=cur_user_email, conference=conf_name)
        except:
            messages.error(
                request, f"Sorry, you are not a reviewer for {conf_name} conference")
            return redirect(conf_views.list_conferences)
        try:
            paper_submission = gsp_dao.get_paper_submission_by_title(
                title)
        except:
            messages.error(
                request, f"Paper {title} doesn't exist")
            return redirect(conf_views.list_conferences)
        try:
            assigned_reviewer_found = AssignedReviewers.objects.find(reviewer=reviewer,
                                                                     paper_submission=paper_submission)
        except:
            messages.error(
                request, f"Sorry, you are not a reviewer for {title} paper")
            return redirect(conf_views.list_conferences)
        # review submission deadline check
        conf = conference_dao.get_conference_by_name(conf_name)
        cur_time = timezone.now()
        if cur_time > conf.review_submission_deadline:
            messages.error(
                request, f"Sorry, review submission deadline has been elapsed")
            return redirect(conf_views.list_conferences)
        if request.method == "POST":
            form = ReviewForm(request.POST)
            if form.is_valid():
                review = form.save(commit=False)
                review.reviewer = reviewer_dao.get_reviewer_by_email_and_conf(
                    request.COOKIES.get('email'), conf_name)
                # paper_submissions = subject_area_submissions_dict[subject_area] = reviewer_dao.get_reviewer_by_email(
                #     request.COOKIES.get('email'))
                review.paper_submission = gsp_dao.get_paper_submission_by_title(
                    title)
                review.save()
                return redirect(conf_views.list_conferences)
        else:
            form = ReviewForm()
        return render(request, "make_review.html", {"is_logged_in": is_logged_in, "form": form})
    return redirect('/accounts/login')


def edit_review(request, conf_name, title):
    is_logged_in = utils.check_login(request)
    if is_logged_in:
        cur_user_email = request.COOKIES.get('email')
        # check if reviewer is assigned to review the paper
        try:
            reviewer = Reviewer.objects.get(
                user=cur_user_email, conference=conf_name)
        except:
            messages.error(
                request, f"Sorry, you are not a reviewer for {conf_name} conference")
            return redirect(conf_views.list_conferences)
        try:
            paper_submission = gsp_dao.get_paper_submission_by_title(
                title)
        except:
            messages.error(
                request, f"Paper {title} doesn't exist")
            return redirect(conf_views.list_conferences)
        try:
            assigned_reviewer_found = AssignedReviewers.objects.find(reviewer=reviewer,
                                                                     paper_submission=paper_submission)
        except:
            messages.error(
                request, f"Sorry, you are not a reviewer for {title} paper")
            return redirect(conf_views.list_conferences)
        # review submission deadline check
        conf = conference_dao.get_conference_by_name(conf_name)
        cur_time = timezone.now()
        if cur_time > conf.review_submission_deadline:
            messages.error(
                request, f"Sorry, review submission deadline has been elapsed")
            return redirect(conf_views.list_conferences)
        review = reviewer_dao.get_review_by_paper_title_and_reviewer(
            title, cur_user_email)
        if request.method == "POST":
            form = ReviewForm(request.POST, instance=review)
            if form.is_valid():
                review = form.save(commit=False)
                review.save()
                return redirect(conf_views.list_conferences)
            return render(request, "edit_review.html", {"is_logged_in": is_logged_in, "form": form})
        else:
            form = ReviewForm(instance=review)
        return render(request, "edit_review.html", {"is_logged_in": is_logged_in, "form": form})
    return redirect('/accounts/login')


def invite_reviewers(request, conf_name):
    is_logged_in = utils.check_login(request)
    if is_logged_in:
        cur_user_email = request.COOKIES.get('email')
        # check if user is CA of the conference or not
        conf_ca_emails = conference_dao.get_a_conference_ca_emails(conf_name)
        if cur_user_email not in conf_ca_emails:
            messages.error(
                request, f"Sorry, you are not a conference admin for {conf_name} conference")
            return redirect(conf_views.list_conferences)
        # invite reviewers deadline check
        conf = conference_dao.get_conference_by_name(conf_name)
        cur_time = timezone.now()
        if (cur_time - conf.paper_submission_deadline).days > INVITE_REVIEWERS_DEADLINE:
            messages.error(
                request, f"Sorry, invite reviewer deadline has been elapsed")
            return redirect(conf_views.list_conferences)

cms/reviewer/templates/apply_as_a_reviewer.html
{% extends 'reviewer_base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
  <h1 class="mt-2">Apply as a reviewer for {{ name }} conference</h1>
  {% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
  {% endif %}
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Apply as a reviewer</button>
  </form>
</div>
{% endblock %}

cms/reviewer/templates/assigned_papers.html
{% extends 'reviewer_base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<h1>Sanity check Assignment Code in reviewer.views.py line 52</h1>

<div class="container">
    <div class="card">
        <h5 class="card-header text-white bg-primary">Papers for Reviewing</h5>
        <div class="card-body text-black bg-light">
            {% if conf_assignments %}
                {% for assignment in conf_assignments %}
                <div class="card">
                    <div class="card-body" style="width: 25rem;">
                        <h5 class="card-title">{{ assignment.title }}</h5>
                        <p class="card-text">{{ assignment.conference.name }}</p>
                        <a href="/reviewer/{{ assignment.conference.name }}/make_review/{{ assignment.title }}" class="btn btn-warning">Make Review</a>
                        <a href="/reviewer/{{ assignment.conference.name }}/edit_review/{{ assignment.title }}" class="btn btn-warning">Edit Review</a>
                    </div>
                </div>
                {% endfor %}
            {% else %}
                <h4>No reviews assigned.</h4>
            {% endif %}
        </div>
        <div class="card-footer bg-white"></div>
    </div>

    <div class="card">
        <h5 class="card-header text-white bg-primary">Papers for Final Area Chair Decision</h5>
        <div class="card-body text-black bg-light">
            {% if ac_assignment %}
                {% for assignment in ac_assignment %}
                <div class="card">
                    <div class="card-body" style="width: 25rem;">
                        <h5 class="card-title">{{ assignment.title }}</h5>
                        <p class="card-text">{{ assignment.conference.name }}</p>
                        <a href="/area_chair/{{ assignment.conference.name }}/make)_decision/{{ assignment.title }}" class="btn btn-warning">Make Decision</a>
                        <a href="/area_chair/{{ assignment.conference.name }}/edit_decision/{{ assignment.title }}" class="btn btn-warning">Edit Decision</a>
                    </div>
                </div>
                {% endfor %}
            {% else %}
                <h4>No Acc-Rej decision assigned.</h4>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

cms/reviewer/templates/automated_reviewer_assignment.html
{% extends 'reviewer_base.html' %}

{% load crispy_forms_tags %}

{% block content %}
{% if messages %}
<ul class="messages">
  {% for message in messages %}
  <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<h1 class="mt-2">Automated reviewer assignment</h1>
<form method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-success">Initiate automated reviewer assignment process</button>
</form>
{% endblock %}

cms/reviewer/templates/edit_review.html
{% extends 'reviewer_base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
  <h1 class="mt-2">Edit review</h1>
  {% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
  {% endif %}
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Edit review</button>
  </form>
</div>
{% endblock %}

cms/reviewer/templates/invite_reviewers.html
{% extends 'reviewer_base.html' %}

{% load template_filters %}

{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
</ul>
{% endif %}
<div class="container">
    <h1 class="mt-2">Invite reviewers</h1>
    <form method="post">
        {% csrf_token %}
        {% for subject_area, uninvited_users in subject_area_uninvited_users_dict.items %}
        <h3 class="mt-2">{{ subject_area }} (Required invitations -
            {{ subject_area_required_invitations|lookup:subject_area }} )
        </h3>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th scope="col">Select User</th>
                                <th scope="col">Institution</th>
                                <th scope="col">Research Interest</th>
                                <th scope="col">Highest degree</th>
                                <th scope="col">Google scholar</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for uninvited_user in uninvited_users %}
                            <tr>
                                <td>
                                    <!-- <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input" id="customCheck1">
                                        <label class="custom-control-label" for="customCheck1"></label>
                                    </div> -->
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" value={{ uninvited_user.email }}
                                            id={{ uninvited_user.email }} name="checked_users">
                                        <label class="form-check-label" for="flexCheckDefault">
                                            {{ uninvited_user.name }}
                                        </label>
                                    </div>
                                </td>
                                {% with uninvited_user.researchprofile_set.all|first as profile %}
                                <td>{{ profile.institution }}</td>
                                <td>{{ profile.research_interests }}</td>
                                <td>{{ profile.highest_degree }}</td>
                                <td>{{ profile.google_scholar }}</td>
                                {% endwith %}
                            </tr>
                            {% endfor %}
                        </tbody>

                    </table>
                </div>
            </div>
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-success">Invite selected reviewers</button>
    </form>
</div>
{% endblock %}

cms/reviewer/templates/make_review.html
{% extends 'reviewer_base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
  <h1 class="mt-2">Make review</h1>
  {% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
  {% endif %}
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Make review</button>
  </form>
</div>
{% endblock %}

cms/reviewer/templates/manual_reviewer_assignment.html
{% extends 'reviewer_base.html' %}

{% block content %}
    <h1 class="mt-2">Manual reviewer assignment</h1>
{% endblock %}

cms/reviewer/templates/reviewer_base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static '/css/style_general.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/style_upper_menu.css' %}">
    <link rel="icon" type="image/ico" href="{% static '/images/favicon.ico' %}">
    <title>Reviewer</title>
  </head>
  <body>

    <ul class="nav justify-content-end border-bottom border-info">
        <li class="nav-item">
            <a href="/accounts/userpage" class="nav-link active">Home</a>
        </li>

        {% if is_logged_in == True %}
        <li class="nav-item">
            <a href="/accounts/assigned_papers" class="nav-link">Assigned Papers</a>
        </li>
        {% endif %}
        
        {% if is_logged_in == False %}
        <li class="nav-item">
            <a href="/accounts/login" class="nav-link">Log In</a>
        </li>
        {% endif %}

        {% if is_logged_in == False %}
        <li class="nav-item">
            <a href="/accounts/signup" class="nav-link">Sign Up</a>
        </li>
        {% endif %}

        {% if is_logged_in == True %}
        <li class="nav-item">
            <a href="/accounts/logout" class="nav-link">Log Out</a>
        </li>
        {% endif %}

    </ul>

  {% block content %}
  {% endblock %}

  </body>
</html>